### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by johnfraney** [ilyankou/Leaflet.IconMaterial#1]
Thanks for this plugin! Before I found this, I hadn't found one that would let me customize both the colour and the icon of map markers.

I think it would be great if you could publish it on NPM so that it's easier to include in other projects.

**Comment by ilyankou** [comment]
Hey @johnfraney:

I'm glad the plugin is what you were looking for! I published it on npm: https://www.npmjs.com/package/leaflet-iconmaterial (my first ever package, so if something is not working - let me know!)

**Comment by johnfraney** [comment]
@ilyankou Congratulations on publishing your first package! I just installed it and it's working well. Thanks for getting that published so quickly.
