### ISSUE TITLE
Marker size

### ISSUE THREAD

**Issue by leocharrua** [ilyankou/Leaflet.IconMaterial#4]
Hello. I'm trying to set the icon size (the marker size) with the iconSize option:

// Create a semi-transparent bus icon
  var busIcon = L.IconMaterial.icon({
    icon: 'directions_bus',            // Name of Material icon
    iconColor: '#aa2187',              // Material icon color (could be rgba, hex, html name...)
    markerColor: 'rgba(255,0,0,0.5)',  // Marker fill color
    outlineColor: 'yellow',            // Marker outline color
    outlineWidth: 1,                   // Marker outline width 

    iconSize:     [38, 95]   // Does not have effect!!!
  })

Is possible to change the size icon with this plugin?

Thanks

**Comment by ilyankou** [comment]
Hey @leocharrua 

I added `iconSize` option, you can update your code and try it.

**Comment by leocharrua** [comment]
It worked!!! Thanks
